spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/survey_db
    username: survey_service
    password: bc93a148-aee8-40b9-ad87-1bb93ffdd46b
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      format_sql: true
      show_sql: true
